<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <RockWebPath>..\RockWeb</RockWebPath>
    <CopyToRockWeb>True</CopyToRockWeb>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="EPPlus">
      <HintPath>..\libs\EPPlus\EPPlus.dll</HintPath>
    </Reference>
    <Reference Include="Quartz">
      <HintPath>..\libs\Quartz\Quartz.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.configuration" />
    <Reference Include="System.Data.Linq" />
    <Reference Include="System.IdentityModel" />
    <Reference Include="System.Security" />
    <Reference Include="System.Threading.Tasks" />
    <Reference Include="System.Web" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="tech.triumph.CloudinaryStorageProvider, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\RockWeb\Bin\tech.triumph.CloudinaryStorageProvider.dll</HintPath>
    </Reference>
    <Reference Include="tech.triumph.WebAgility, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\RockWeb\Bin\tech.triumph.WebAgility.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotLiquid\DotLiquid.csproj" />
    <ProjectReference Include="..\Rock.Common\Rock.Common.csproj" />
    <ProjectReference Include="..\Rock.Enums\Rock.Enums.csproj" />
    <ProjectReference Include="..\Rock.Lava.Shared\Rock.Lava.Shared.csproj" />
    <ProjectReference Include="..\Rock\Rock.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Flurl" Version="2.6.0" />
    <PackageReference Include="Microsoft.Graph" Version="1.21.0" />
    <PackageReference Include="Microsoft.Graph.Auth" Version="1.0.0-preview.6" />
    <PackageReference Include="Microsoft.Graph.Core" Version="1.23.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.61.3" />
    <PackageReference Include="Microsoft.IdentityModel.Abstractions" Version="6.35.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="RestSharp" Version="105.2.3" />
    <PackageReference Include="SquaredUp.HubSpot.NET" Version="0.6.17" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    <PackageReference Include="System.Runtime" Version="4.3.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Security.Principal" Version="4.3.0" />
  </ItemGroup>
</Project>